### ISSUE TITLE
random_idxs = random_idxs + 257 ?

### ISSUE THREAD

**Issue by gaslen** [Hua-YS/Semantic-Segmentation-with-Sparse-Labels#1]
Hello, thank you for your work!
I have a small question:
In the loss. py file at line 9, why do you do
`random_idxs = random_idxs + 257` please ?

**Comment by Hua-YS** [comment]
Hi Gaslen, this is a good question. The reason is that we randomly select pixels from the inner region and **did not consider those on boundaries**.

If you check line 8, you can see the **range** we randomly select pixels is **(h-2) x (w-2)**. Therefore, we need to "+257" to transfer coordinates in the inner region to the whole 256 x 256 image.

The reason we don't consider pixels on boundaries is to simplify the following calculation (line 48 -55). Otherwise, these lines can be super complicated. Hope this answer helps.

**Comment by gaslen** [comment]
Ok, I understand! Thank you for the quick answer :)
